# Generated by Django 6.0.4 on 2026-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
