# Generated by Django 6.0.4 on 2026-05-19 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_master_description_alter_service_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermessage',
            name='is_from_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mastermessage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mastermessage',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='beauty.master'),
        ),
    ]
