# Generated by Django 6.0.4 on 2026-05-19 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_mastermessage_is_from_master_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastermessage',
            name='is_from_master',
        ),
        migrations.AddField(
            model_name='mastermessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastermessage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mastermessage',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.master'),
        ),
    ]
